### ISSUE TITLE
Type error for number arithmetic function

### ISSUE THREAD

**Issue by MainShayne233** [gyson/ex_type#5]
Hey! Super cool project! I'm interested in seeing what comes from it.

When playing around with it, I found that the following code:

```elixir
defmodule Client do

  @spec add(number(), number()) :: number()
  def add(x, y) do
    x + y
  end
end
```

produces the following type error:
```
❯ mix type
Compiling 1 file (.ex)
❌  Client.add/2
   |
   | type error for :erlang.+/2 with :erlang.+(integer() | float(), integer() | float())
   |
   | at /home/shayne/elixir/type_hooks/lib/client.ex:5
```

Is there a reason why this type check fails? Does `ex_type` require stricter types than unions like `number()`? If this is not a bug, what could the error message be to make the type issue more clear?

Thanks!

**Comment by gyson** [comment]
Thanks for reporting!

It should be resolved with #8 now.
